sudo: required

services:
  - docker

before_script:
  - docker-compose up -d --build

script:
  - docker-compose exec --user $UID app composer update
  - docker-compose exec --user $UID app vendor/bin/phpunit --debug

after_script:
  - docker-compose down --rmi local -v
